name: negotiation-rl-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.9
  - pip
  - pip:
      - gymnasium==1.0.0
      - numpy==1.26.4
      - pandas==2.1.3
      - torch==2.2.2
      - stable-baselines3[extra]==2.4.1
      - tensorboard==2.19.0
      - wandb==0.19.11
      - pyarrow==20.0.0
